[nfs]
172.31.22.200 ansible_ssh-user='ec2-user'

[webservers]
172.31.28.193 ansible_ssh-user='ec2-user'
172.31.20.108 ansible_ssh-user='ec2-user'

[db]
172.31.20.242 ansible_ssh-user='ubuntu'

[lb]
172.31.17.210 ansible_ssh-user='ubuntu'